#!/usr/bin/env node
import { report } from './report.js';

const command = process.argv[2];

if (command === 'mcp') {
  // Non-literal specifier: dist/stdio.js is generated by `xmcp build` and doesn't
  // exist as a source file, so a literal import() would fail module resolution
  // at typecheck time even though it exists at runtime after the build.
  const stdioEntry = '../dist/stdio.js';
  await import(stdioEntry);
} else if (command === 'report') {
  process.exitCode = await report(process.argv.slice(3));
} else {
  console.log('Usage: trust-gate <mcp|report>');
  console.log('  mcp     Starts the trust-gate MCP stdio server for the current tool calls.');
  console.log('  report  Runs check_regression and optionally posts the verdict to a backend.');
  process.exitCode = command ? 1 : 0;
}
