#!/usr/bin/env node
export {};

const command = process.argv[2];

if (command === 'mcp') {
  // Non-literal specifier: dist/stdio.js is generated by `xmcp build` and doesn't
  // exist as a source file, so a literal import() would fail module resolution
  // at typecheck time even though it exists at runtime after the build.
  const stdioEntry = '../dist/stdio.js';
  await import(stdioEntry);
} else {
  console.log('Usage: trust-gate mcp');
  console.log('  Starts the trust-gate MCP stdio server for the current tool calls.');
  process.exitCode = command ? 1 : 0;
}
